import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { asset, detectImage, detectSample, DetectionResult, getJson, Sample } from "./api/client";
import { EvidenceStrip } from "./components/EvidenceStrip";
import { Icon } from "./components/Icon";

type View = "overview" | "detect" | "evaluation" | "errors" | "models" | "scope";
type Metrics = { map_50_95:number; ap50:number; ap75:number; precision_at_50:number; recall_at_50:number; count_mae:number; count_rmse:number; count_mean_bias:number; profile:string };
type Density = { density:string; map_50_95:number; ap50:number; count_mae:number; recall_at_50:number; images:number };
type ErrorItem = { image_id:string; image_url:string; overlay_url:string; density:string; truth_count:number; predicted_count:number; count_error:number; false_positive:number; false_negative:number };
type ModelReport = { selected_model:string; warning:string; models:Array<Record<string,string|number|boolean>> };

const navigation: Array<{id:View;label:string;icon:string}> = [
  {id:"overview",label:"Overview",icon:"overview"},{id:"detect",label:"Detect",icon:"detect"},
  {id:"evaluation",label:"Evaluation",icon:"chart"},{id:"errors",label:"Count errors",icon:"errors"},
  {id:"models",label:"Model registry",icon:"model"},{id:"scope",label:"Responsible scope",icon:"scope"}
];

function pct(value:number){return `${(value*100).toFixed(1)}%`}
function Metric({label,value,note,accent=false}:{label:string;value:string;note:string;accent?:boolean}){return <article className={`metric ${accent?"accent":""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}

function Overview({metrics,onStart}:{metrics:Metrics|null;onStart:()=>void}){
  return <section className="page overview"><div className="hero"><div><p className="eyebrow">Computer vision - Project 20</p><h1>Count what is <span>actually visible.</span></h1><p className="lead">A dense-scene detection console that keeps boxes, thresholds, counting error and compute profile attached to every decision.</p><div className="actions"><button className="primary" onClick={onStart}>Inspect a shelf <b aria-hidden="true">&rarr;</b></button><a href="/docs" target="_blank" rel="noreferrer">API contract</a></div></div><div className="shelf-graphic" aria-label="Abstract dense shelf detection graphic">{Array.from({length:42},(_,i)=><i key={i} style={{"--delay":`${(i%7)*35}ms`} as React.CSSProperties}/>)}</div></div><EvidenceStrip/><div className="metrics"><Metric label="Qualification scenes" value="12" note="Deterministic and public"/><Metric label="Visible objects" value="740" note="One class: object"/><Metric label="Count MAE" value={metrics?metrics.count_mae.toFixed(2):"--"} note="Procedural validation" accent/><Metric label="Official test" value="Locked" note="No tuning leakage"/></div><div className="split"><article className="panel"><p className="eyebrow">Detection chain</p><h2>Geometry remains observable.</h2><div className="pipeline">{[["01","Decode","Safe RGB input"],["02","Detect","Candidate regions"],["03","Suppress","NMS with visible IoU"],["04","Count","Boxes become a visible count"],["05","Measure","AP and count error stay separate"]].map(([n,t,c])=><div key={n}><span>{n}</span><b>{t}</b><small>{c}</small></div>)}</div></article><article className="panel boundary"><p className="eyebrow">Product boundary</p><h2>Object presence, not inventory truth.</h2><ul><li>Single class: <code>object</code></li><li>No brand, SKU or price recognition</li><li>No hidden-stock estimate</li><li>No real-time claim without hardware evidence</li></ul></article></div></section>
}

function Detector({samples}:{samples:Sample[]}){
  const [sample,setSample]=useState<Sample|null>(samples[0]??null); const [file,setFile]=useState<File|null>(null);
  const [preview,setPreview]=useState(sample?asset(sample.image_url):""); const [result,setResult]=useState<DetectionResult|null>(null);
  const [confidence,setConfidence]=useState(.35); const [iou,setIou]=useState(.45); const [zoom,setZoom]=useState(1);
  const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{if(!sample&&samples.length&&!file){setSample(samples[0]);setPreview(asset(samples[0].image_url))}},[samples,sample,file]);
  function choose(next:Sample){setSample(next);setFile(null);setPreview(asset(next.image_url));setResult(null)}
  function upload(event:ChangeEvent<HTMLInputElement>){const next=event.target.files?.[0];if(!next)return;setFile(next);setSample(null);setPreview(URL.createObjectURL(next));setResult(null)}
  async function run(){setBusy(true);setError("");try{setResult(file?await detectImage(file,file.name,confidence,iou):sample?await detectSample(sample,confidence,iou):null)}catch(reason){setError(reason instanceof Error?reason.message:"Detection failed")}finally{setBusy(false)}}
  return <section className="page"><header className="page-title"><div><p className="eyebrow">Inference canvas</p><h1>See every accepted box.</h1><p>Adjust thresholds, rerun the same artifact and inspect the operational count.</p></div><span className="ready"><i/> Bundle ready</span></header><EvidenceStrip/>{error&&<div className="error"><b>Detection unavailable</b><span>{error}</span></div>}<div className="workspace"><article className="panel canvas-panel"><div className="panel-head"><div><p className="eyebrow">Shelf scene</p><h2>Visual inspection</h2></div><label className="upload">Upload image<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/></label></div><div className="canvas-viewport"><div className="canvas" style={{transform:`scale(${zoom})`}}>{preview&&<img src={preview} alt="Shelf selected for detection"/>}{result&&<svg viewBox={`0 0 ${result.image_width} ${result.image_height}`} aria-label={`${result.visible_count} detection boxes`}>{result.detections.map(box=><g key={box.detection_id}><rect x={box.box[0]} y={box.box[1]} width={box.box[2]-box.box[0]} height={box.box[3]-box.box[1]}/><text x={box.box[0]+3} y={box.box[1]+12}>{box.detection_id+1}</text></g>)}</svg>}</div></div><div className="samples">{samples.slice(0,6).map(item=><button key={item.image_id} className={sample?.image_id===item.image_id?"selected":""} onClick={()=>choose(item)}><img src={asset(item.image_url)} alt={`${item.density} density shelf`}/><span>{item.density} - {item.truth_count}</span></button>)}</div></article><aside className="panel controls"><p className="eyebrow">Operating point</p><h2>Detection controls</h2><label htmlFor="confidence">Confidence <output>{confidence.toFixed(2)}</output></label><input id="confidence" type="range" min="0.05" max="0.95" step="0.05" value={confidence} onChange={e=>setConfidence(Number(e.target.value))}/><label htmlFor="iou">NMS IoU <output>{iou.toFixed(2)}</output></label><input id="iou" type="range" min="0.1" max="0.9" step="0.05" value={iou} onChange={e=>setIou(Number(e.target.value))}/><label htmlFor="zoom">Canvas zoom <output>{zoom.toFixed(1)}x</output></label><input id="zoom" type="range" min="0.6" max="1.8" step="0.1" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/><button className="primary wide" onClick={run} disabled={busy||(!sample&&!file)}>{busy?"Running detector...":"Run detector"}<b aria-hidden="true">&rarr;</b></button>{result?<ResultSummary result={result}/>:<div className="empty"><Icon name="detect"/><b>No detections yet</b><span>Run the selected image to populate boxes and the table.</span></div>}</aside></div>{result&&<DetectionTable result={result}/>}</section>
}

function ResultSummary({result}:{result:DetectionResult}){return <div className="result-summary"><div><span>Visible count</span><strong>{result.visible_count}</strong></div><div><span>Latency</span><strong>{result.latency_ms.toFixed(1)} ms</strong></div><small>{result.model_version}</small><p>{result.warnings[0]}</p></div>}
function DetectionTable({result}:{result:DetectionResult}){return <article className="panel detections"><div className="panel-head"><div><p className="eyebrow">Accepted detections</p><h2>{result.visible_count} visible objects</h2></div><code>{result.request_id.slice(0,8)}</code></div><div className="table"><div className="row header"><span>ID</span><span>Class</span><span>Confidence</span><span>XYXY box</span></div>{result.detections.slice(0,60).map(item=><div className="row" key={item.detection_id}><b>#{String(item.detection_id+1).padStart(3,"0")}</b><span>{item.class_name}</span><span>{pct(item.confidence)}</span><code>{item.box.map(Math.round).join(" - ")}</code></div>)}</div>{result.detections.length>60&&<p className="table-note">Showing the first 60 detections to keep dense scenes responsive.</p>}</article>}

function Evaluation({metrics,slices}:{metrics:Metrics|null;slices:Density[]}){return <section className="page"><header className="page-title"><div><p className="eyebrow">Evaluation profile</p><h1>AP and count error are not interchangeable.</h1><p>All values below come from persisted qualification predictions.</p></div></header><EvidenceStrip/>{metrics&&<><div className="metrics"><Metric label="mAP@[.50:.95]" value={pct(metrics.map_50_95)} note="Qualification only"/><Metric label="AP50 / AP75" value={`${pct(metrics.ap50)} / ${pct(metrics.ap75)}`} note="Localization quality"/><Metric label="Precision / recall" value={`${pct(metrics.precision_at_50)} / ${pct(metrics.recall_at_50)}`} note="IoU 0.50"/><Metric label="Count RMSE" value={metrics.count_rmse.toFixed(2)} note={`Bias ${metrics.count_mean_bias.toFixed(2)}`}/></div><div className="density-grid">{slices.map(slice=><article className="panel density" key={slice.density}><span>{slice.density} density</span><strong>{pct(slice.map_50_95)}</strong><small>mAP@[.50:.95]</small><div><b>{slice.images}</b> scenes <b>{slice.count_mae.toFixed(2)}</b> count MAE</div></article>)}</div></>}</section>}

function Errors({items}:{items:ErrorItem[]}){return <section className="page"><header className="page-title"><div><p className="eyebrow">Error slicing</p><h1>Inspect the count delta.</h1><p>Teal boxes are truth; amber boxes are model predictions.</p></div></header><EvidenceStrip/><div className="error-gallery">{items.map(item=><article className="error-card" key={item.image_id}><img src={asset(item.overlay_url)} alt={`Overlay for ${item.image_id}`}/><div><span>{item.density}</span><h2>{item.count_error>0?`+${item.count_error}`:item.count_error} count error</h2><p>{item.truth_count} truth - {item.predicted_count} predicted</p><small>{item.false_positive} FP - {item.false_negative} FN</small></div></article>)}</div></section>}

function Models({report}:{report:ModelReport|null}){return <section className="page"><header className="page-title"><div><p className="eyebrow">Candidate registry</p><h1>Execution state before leaderboard.</h1><p>Unrun YOLO and Faster R-CNN candidates carry no estimated metrics.</p></div></header>{report&&<><div className="selection"><span>Selected qualification artifact</span><strong>{report.selected_model}</strong><p>{report.warning}</p></div><div className="model-table"><div className="model-row header"><span>Candidate</span><span>Status</span><span>mAP</span><span>Count MAE</span></div>{report.models.map(model=><div className="model-row" key={String(model.model_id)}><b>{String(model.model_id)}</b><span className={String(model.status)}>{String(model.status).replaceAll("_"," ")}</span><span>{typeof model.map_50_95==="number"?pct(model.map_50_95):"Not reported"}</span><span>{typeof model.count_mae==="number"?Number(model.count_mae).toFixed(2):"Not reported"}</span></div>)}</div></>}</section>}

function Scope(){return <section className="page"><header className="page-title"><div><p className="eyebrow">Responsible scope</p><h1>A visible box is not a stock record.</h1><p>Operational boundaries remain part of the product surface.</p></div></header><div className="principles">{[["01","Single class","Every accepted detection is object. The console does not identify a product, brand, price or SKU."],["02","Visible count","The count covers visible instances in one image and cannot infer products behind the first row."],["03","Profile attached","Smoke, development and full results cannot be mixed; only qualification smoke exists today."],["04","Threshold transparency","Confidence and NMS IoU are returned with every response and are user-visible controls."],["05","No real-time claim","Latency is local qualification evidence, not a production SLA or edge-device benchmark."],["06","Official test lock","SKU-110K test stays unopened until a trained candidate and thresholds are selected on validation."]].map(([n,t,c])=><article className="panel principle" key={n}><span>{n}</span><h2>{t}</h2><p>{c}</p></article>)}</div></section>}

export function App(){const[view,setView]=useState<View>("overview");const[ready,setReady]=useState(false);const[metrics,setMetrics]=useState<Metrics|null>(null);const[samples,setSamples]=useState<Sample[]>([]);const[slices,setSlices]=useState<Density[]>([]);const[errors,setErrors]=useState<ErrorItem[]>([]);const[models,setModels]=useState<ModelReport|null>(null);const[loadError,setLoadError]=useState("");useEffect(()=>{Promise.all([getJson<{status:string}>("/ready"),getJson<Metrics>("/v1/evaluation/summary"),getJson<{items:Sample[]}>("/v1/samples"),getJson<{slices:Density[]}>("/v1/evaluation/density-slices"),getJson<{items:ErrorItem[]}>("/v1/evaluation/errors"),getJson<ModelReport>("/v1/evaluation/models")]).then(([r,m,s,d,e,mo])=>{setReady(r.status==="ready");setMetrics(m);setSamples(s.items);setSlices(d.slices);setErrors(e.items);setModels(mo)}).catch(reason=>setLoadError(reason instanceof Error?reason.message:"API unavailable"))},[]);const content=useMemo(()=>view==="overview"?<Overview metrics={metrics} onStart={()=>setView("detect")}/>:view==="detect"?<Detector samples={samples}/>:view==="evaluation"?<Evaluation metrics={metrics} slices={slices}/>:view==="errors"?<Errors items={errors}/>:view==="models"?<Models report={models}/>:<Scope/>,[view,metrics,samples,slices,errors,models]);return <div className="shell"><aside><div className="brand"><div><Icon name="detect"/></div><section><strong>Shelf Lens</strong><span>Detection operations</span></section></div><p>Workspace</p><nav>{navigation.map(item=><button key={item.id} className={view===item.id?"active":""} onClick={()=>setView(item.id)}><Icon name={item.icon}/><span>{item.label}</span></button>)}</nav><div className="rail-status"><i className={ready?"":"offline"}/><div><b>{ready?"Workspace ready":"Setup required"}</b><small>Single class - qualification</small></div></div></aside><main><header className="topbar"><div><small>AI Engineer - Project 20</small><strong>{navigation.find(item=>item.id===view)?.label}</strong></div><span className="environment"><i className={ready?"":"offline"}/>{ready?"Local engine":"Engine offline"}</span></header>{loadError&&<div className="global-error"><b>Evidence service unavailable</b><span>{loadError}</span></div>}{content}</main></div>}



