import { useEffect, useMemo, useState } from "react";
import { exportExtraction, extractSample, extractUpload, loadWorkspace, resolveApiUrl } from "./api/client";
import type { ErrorEntry, EvaluationSummary, Extraction, FieldName, ModelRecord, Sample } from "./api/types";
import { DocumentCanvas } from "./components/DocumentCanvas";
import { Icon } from "./components/Icon";

type Page = "overview" | "extract" | "reading" | "evaluation" | "errors" | "model";
interface Workspace { samples: Sample[]; model: ModelRecord; summary: EvaluationSummary; errors: ErrorEntry[] }

const navigation: Array<{ id: Page; label: string; icon: Parameters<typeof Icon>[0]["name"] }> = [
  { id: "overview", label: "Overview", icon: "grid" },
  { id: "extract", label: "Extract document", icon: "document" },
  { id: "reading", label: "Reading order", icon: "scan" },
  { id: "evaluation", label: "Evaluation", icon: "chart" },
  { id: "errors", label: "Error gallery", icon: "alert" },
  { id: "model", label: "Model record", icon: "model" }
];

function percent(value: number, digits = 1) { return `${(value * 100).toFixed(digits)}%`; }

function SectionHeading({ eyebrow, title, copy }: { eyebrow: string; title: string; copy: string }) {
  return <header className="section-heading"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p></header>;
}

function Metric({ label, value, detail, tone = "neutral" }: { label: string; value: string; detail: string; tone?: string }) {
  return <article className={`metric metric-${tone}`}><span>{label}</span><strong>{value}</strong><p>{detail}</p></article>;
}

function Overview({ workspace, onStart }: { workspace: Workspace; onStart: () => void }) {
  return <div className="page-stack">
    <section className="hero">
      <div className="hero-copy"><span className="eyebrow">DOCUMENT INTELLIGENCE · WITH RECEIPTS</span><h1>From pixels to proof,<br/><em>not just fields.</em></h1><p>Extract business values with the exact OCR lines, regions, confidence and normalization decisions that produced them.</p><div className="hero-actions"><button className="button primary" onClick={onStart}>Open workbench <Icon name="arrow"/></button><a className="button secondary" href="/docs" target="_blank">API contract</a></div></div>
      <div className="hero-document" aria-hidden="true"><div className="paper-sheet"><i className="paper-line wide"/><i className="paper-line"/><i className="paper-line short"/><div className="paper-field field-a">COMPANY</div><div className="paper-field field-b">DATE</div><div className="paper-field field-c">TOTAL</div><span className="scan-beam"/></div><span className="orbit-tag tag-one">OCR</span><span className="orbit-tag tag-two">KIE</span><span className="orbit-tag tag-three">REVIEW</span></div>
    </section>
    <section className="metric-grid"><Metric label="Qualification documents" value={String(workspace.summary.documents)} detail="Generated and sealed fixtures"/><Metric label="Field exact match" value={percent(workspace.summary.end_to_end.normalized_field_exact_match)} detail="Normalized end-to-end output" tone="good"/><Metric label="OCR character error" value={percent(workspace.summary.ocr.cer, 2)} detail="Lower is better"/><Metric label="Review rate" value={percent(workspace.summary.end_to_end.review_rate)} detail="Fields routed to an operator" tone="review"/></section>
    <section className="split-grid"><article className="panel pipeline"><div className="panel-head"><div><span className="eyebrow">AUDITABLE PIPELINE</span><h2>One record, six accountable stages.</h2></div><Icon name="scan"/></div><div className="pipeline-steps">{["Validate", "Preprocess", "Localize", "Recognize", "Normalize", "Review"].map((step,index)=><div key={step}><span>{String(index+1).padStart(2,"0")}</span><strong>{step}</strong>{index<5&&<Icon name="arrow"/>}</div>)}</div></article><article className="panel evidence-boundary"><span className="eyebrow">EVIDENCE BOUNDARY</span><h2>SROIE is not silently substituted.</h2><p>The live demo uses repository-authored qualification receipts. Official SROIE remains locked until its original data and splits are verified.</p><dl><div><dt>Fixture OCR</dt><dd>Available</dd></div><div><dt>Upload OCR</dt><dd>Optional runtime</dd></div><div><dt>Official benchmark</dt><dd>Not claimed</dd></div></dl></article></section>
  </div>;
}

function ExtractPage({ workspace, extraction, setExtraction }: { workspace: Workspace; extraction: Extraction | null; setExtraction: (value: Extraction) => void }) {
  const [sampleId, setSampleId] = useState(workspace.samples[0]?.sample_id ?? "");
  const [file, setFile] = useState<File | null>(null);
  const [profile, setProfile] = useState("deskew-clahe-v1");
  const [running, setRunning] = useState(false);
  const [error, setError] = useState("");
  const [activeField, setActiveField] = useState<FieldName | null>("total");
  const [edits, setEdits] = useState<Partial<Record<FieldName, string>>>({});

  async function run() {
    setRunning(true); setError(""); setEdits({});
    try { setExtraction(file ? await extractUpload(file, profile) : await extractSample(sampleId, profile)); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Extraction failed."); }
    finally { setRunning(false); }
  }

  useEffect(() => { if (!extraction && sampleId) void run(); }, []);
  const reviewCount = extraction?.fields.filter((field) => field.review_required).length ?? 0;
  return <div className="page-stack">
    <SectionHeading eyebrow="LIVE EXTRACTION" title="Read the document. Keep the evidence." copy="Select a sealed receipt or connect a real OCR runtime for your own image. Predictions and operator edits remain separate."/>
    <section className="workbench-grid">
      <aside className="panel source-tray"><div className="panel-head"><div><span className="eyebrow">INPUT SOURCE</span><h2>Qualification tray</h2></div><span className="count-chip">{workspace.samples.length}</span></div><div className="sample-grid">{workspace.samples.map(sample=><button key={sample.sample_id} className={sampleId===sample.sample_id&&!file?"sample active":"sample"} onClick={()=>{setSampleId(sample.sample_id);setFile(null)}}><img src={resolveApiUrl(sample.image_url)} alt="Receipt preview"/><span>{sample.sample_id.replace("receipt-","").replaceAll("-"," ")}</span><small>{sample.locale}</small></button>)}</div><label className="upload"><Icon name="upload"/><span><strong>{file?.name??"Upload JPEG, PNG or PDF"}</strong><small>Max 8 MB · single page</small></span><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={event=>setFile(event.target.files?.[0]??null)}/></label><label className="select-label">Preprocessing profile<select value={profile} onChange={event=>setProfile(event.target.value)}><option value="original-v1">Original · validation baseline</option><option value="deskew-clahe-v1">Deskew + CLAHE</option><option value="adaptive-threshold-v1">Adaptive threshold</option></select></label><button className="button primary wide" disabled={running} onClick={run}>{running?"Extracting evidence…":"Run extraction"}<Icon name="arrow"/></button>{error&&<div className="error-banner" role="alert"><Icon name="alert"/><span>{error}</span></div>}</aside>
      <section className="evidence-column">{extraction?<><article className="panel document-panel"><div className="document-toolbar"><div><span className="eyebrow">DOCUMENT CANVAS</span><strong>{extraction.source_name}</strong></div><div><span>{extraction.ocr_adapter}</span><span>{extraction.preprocessing_profile}</span></div></div><DocumentCanvas extraction={extraction} activeField={activeField} onField={setActiveField}/></article><article className="panel field-panel"><div className="panel-head"><div><span className="eyebrow">NORMALIZED OUTPUT</span><h2>Four fields. Every source visible.</h2></div><span className={reviewCount?"review-chip":"ready-chip"}>{reviewCount?`${reviewCount} review` : "Ready"}</span></div><div className="field-table"><div className="field-row field-head"><span>Field</span><span>Raw OCR</span><span>Normalized / edited</span><span>Confidence</span></div>{extraction.fields.map(field=><div className={`field-row ${activeField===field.field?"field-active":""}`} key={field.field} onClick={()=>setActiveField(field.field)}><strong>{field.field}</strong><span>{field.raw_value??"—"}</span><label><Icon name="edit"/><input value={edits[field.field]??field.normalized_value??""} onChange={event=>setEdits({...edits,[field.field]:event.target.value})} aria-label={`Edit ${field.field}`}/></label><span className={field.review_required?"confidence review":"confidence"}>{percent(field.confidence)}</span></div>)}</div><div className="export-row"><div><span>Operator edits</span><strong>{Object.keys(edits).length} separate from predictions</strong></div><button className="button secondary" onClick={()=>void exportExtraction(extraction.request_id,"csv",Object.entries(edits).map(([field,value])=>({field,value:value!})))}><Icon name="download"/>CSV</button><button className="button dark" onClick={()=>void exportExtraction(extraction.request_id,"json",Object.entries(edits).map(([field,value])=>({field,value:value!})))}><Icon name="download"/>JSON</button></div></article></>:<div className="panel empty"><span className="empty-orbit"/><h2>No extraction yet</h2><p>Choose a sealed receipt and run the evidence pipeline.</p></div>}</section>
    </section>
  </div>;
}

function ReadingPage({ extraction, openExtract }: { extraction: Extraction | null; openExtract: () => void }) {
  if(!extraction) return <div className="page-stack"><SectionHeading eyebrow="OCR TRACE" title="Reading order starts with an extraction." copy="Run one document first; this view never fabricates OCR tokens."/><div className="panel empty"><Icon name="scan"/><h2>No OCR record loaded</h2><button className="button primary" onClick={openExtract}>Extract a document</button></div></div>;
  return <div className="page-stack"><SectionHeading eyebrow="OCR TRACE" title="See what the reader saw." copy="Every OCR line retains its order, geometry and recognition confidence before field logic begins."/><section className="reading-layout"><article className="panel reading-document"><DocumentCanvas extraction={extraction} activeField={null} onField={()=>undefined}/></article><article className="panel token-ledger"><div className="panel-head"><div><span className="eyebrow">READING LEDGER</span><h2>{extraction.tokens.length} localized lines</h2></div><span className="count-chip">top → bottom</span></div><ol>{extraction.tokens.map(token=><li key={token.token_id}><span>{String(token.line_index+1).padStart(2,"0")}</span><div><strong>{token.text}</strong><small>{token.box.join(" · ")}</small></div><em className={token.confidence<.84?"low":""}>{percent(token.confidence)}</em></li>)}</ol><div className="ledger-foot"><span>Raw OCR remains immutable</span><strong>{extraction.request_id.slice(0,12)}</strong></div></article></section></div>;
}

function EvaluationPage({ summary }: { summary: EvaluationSummary }) {
  return <div className="page-stack"><SectionHeading eyebrow="QUALIFICATION EVIDENCE" title="Measure the reader and the extractor separately." copy="OCR error, localization, normalized field exact match and review pressure are reported without collapsing the system into one flattering score."/><section className="metric-grid"><Metric label="Character error rate" value={percent(summary.ocr.cer,2)} detail="Edit distance over characters"/><Metric label="Word error rate" value={percent(summary.ocr.wer,2)} detail="Edit distance over whitespace tokens"/><Metric label="Line exact match" value={percent(summary.ocr.line_exact_match)} detail="Whole-line transcription"/><Metric label="Document exact" value={percent(summary.end_to_end.document_exact_match)} detail="All four normalized fields" tone="review"/></section><section className="evaluation-grid"><article className="panel comparison-bars"><div className="panel-head"><div><span className="eyebrow">ERROR PROPAGATION</span><h2>Oracle OCR vs end-to-end</h2></div></div><div className="bar-comparison"><div><label><span>Oracle field exact</span><strong>{percent(summary.oracle_ocr.normalized_field_exact_match)}</strong></label><i><b style={{width:percent(summary.oracle_ocr.normalized_field_exact_match)}}/></i></div><div><label><span>End-to-end field exact</span><strong>{percent(summary.end_to_end.normalized_field_exact_match)}</strong></label><i><b style={{width:percent(summary.end_to_end.normalized_field_exact_match)}}/></i></div><div><label><span>End-to-end document exact</span><strong>{percent(summary.end_to_end.document_exact_match)}</strong></label><i><b style={{width:percent(summary.end_to_end.document_exact_match)}}/></i></div></div><p>{summary.interpretation}</p></article><article className="panel localization-card"><span className="eyebrow">LOCALIZATION @ IOU 0.5</span><h2>Regions stay attached to text.</h2><div><span>Precision<strong>{percent(summary.ocr.localization_precision_iou_0_5)}</strong></span><span>Recall<strong>{percent(summary.ocr.localization_recall_iou_0_5)}</strong></span></div><p>These localization results apply only to sealed annotations where fixture regions and predictions share geometry.</p></article></section><section className="scope-warning"><Icon name="alert"/><div><strong>Qualification scope only</strong><p>{summary.evidence_scope}. No external generalization claim is made.</p></div></section></div>;
}

function ErrorsPage({ errors }: { errors: ErrorEntry[] }) {
  return <div className="page-stack"><SectionHeading eyebrow="FAILURE ANALYSIS" title="Review the field that broke the document." copy="The gallery includes mismatches and low-confidence review decisions generated by the reproducible qualification run."/><section className="error-grid">{errors.map(error=><article className="error-card panel" key={`${error.sample_id}-${error.field}`}><div><span className="error-field">{error.field}</span><span className="review-chip">{percent(error.confidence)} confidence</span></div><h2>{error.sample_id.replaceAll("-"," ")}</h2><dl><div><dt>Expected</dt><dd>{error.expected}</dd></div><div><dt>Predicted</dt><dd>{error.predicted??"Missing"}</dd></div></dl><footer>{error.reason_codes.map(reason=><span key={reason}>{reason.replaceAll("_"," ")}</span>)}</footer></article>)}</section>{!errors.length&&<div className="panel empty"><Icon name="check"/><h2>No recorded errors</h2><p>The report is empty; no synthetic error card will be invented.</p></div>}</div>;
}

function ModelPage({ model }: { model: ModelRecord }) {
  return <div className="page-stack"><SectionHeading eyebrow="VERSIONED SYSTEM RECORD" title="Know which capability produced the field." copy="OCR adapter, field extractor, evaluation protocol and evidence boundary travel together in one hash-verified bundle."/><section className="model-grid"><article className="panel model-card"><div className="model-mark"><Icon name="model"/></div><span className="eyebrow">APPROVED BUNDLE</span><h2>{model.bundle_id}</h2><p>{model.release}</p><span className="ready-chip">{model.status}</span><dl><div><dt>Sealed OCR</dt><dd>{model.ocr}</dd></div><div><dt>Upload OCR</dt><dd>{model.upload_ocr}</dd></div><div><dt>Extractor</dt><dd>{model.extractor}</dd></div><div><dt>Protocol</dt><dd>{model.evaluation_protocol}</dd></div></dl></article><article className="panel boundary-register"><span className="eyebrow">BOUNDARY REGISTER</span><h2>What is and is not available</h2>{Object.entries(model.evidence_boundary).map(([key,value])=><div key={key}><span>{key.replaceAll("_"," ")}</span><strong>{value}</strong></div>)}<p>Runtime errors remain visible. Missing OCR dependencies never fall back to generated text.</p></article></section></div>;
}

export default function App() {
  const [page,setPage]=useState<Page>("overview"); const [workspace,setWorkspace]=useState<Workspace|null>(null); const [extraction,setExtraction]=useState<Extraction|null>(null); const [error,setError]=useState("");
  useEffect(()=>{loadWorkspace().then(setWorkspace).catch(reason=>setError(reason instanceof Error?reason.message:"Workspace unavailable."));},[]);
  const pageLabel=useMemo(()=>navigation.find(item=>item.id===page)?.label??"Workspace",[page]);
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Icon name="document"/></div><div><strong>LedgerLens</strong><span>Document evidence</span></div></div><nav aria-label="Workbench navigation">{navigation.map(item=><button key={item.id} className={page===item.id?"active":""} onClick={()=>setPage(item.id)}><Icon name={item.icon}/><span>{item.label}</span>{page===item.id&&<i/>}</button>)}</nav><div className="sidebar-status"><span><i/> Extraction service</span><strong>{workspace?"Ready":"Connecting"}</strong><small>Plan 04 · Project 22</small></div></aside><main><header className="topbar"><div><span>AI ENGINEER · PROJECT 22</span><strong>{pageLabel}</strong></div><div><span className="environment"><i/>Qualification workspace</span><span className="operator">DV</span></div></header><div className="content">{error&&<div className="fatal"><Icon name="alert"/><h1>Evidence workspace unavailable</h1><p>{error}</p><button className="button primary" onClick={()=>location.reload()}>Retry</button></div>}{!workspace&&!error&&<div className="loading"><span className="loader"/><p>Verifying bundle hashes</p><h1>Preparing the workbench.</h1></div>}{workspace&&<><div className="status-strip"><span><i/>Bundle ready</span><span>{workspace.model.release}</span><span>{workspace.model.extractor}</span><span className="locked">Official SROIE locked</span></div>{page==="overview"&&<Overview workspace={workspace} onStart={()=>setPage("extract")}/>} {page==="extract"&&<ExtractPage workspace={workspace} extraction={extraction} setExtraction={setExtraction}/>} {page==="reading"&&<ReadingPage extraction={extraction} openExtract={()=>setPage("extract")}/>} {page==="evaluation"&&<EvaluationPage summary={workspace.summary}/>} {page==="errors"&&<ErrorsPage errors={workspace.errors}/>} {page==="model"&&<ModelPage model={workspace.model}/>}</>}</div></main></div>;
}
